openapi: 3.0.0
info:
  title: Email Sender API
  version: 1.0.0

paths:
  /send-email:
    post:
      summary: Send an email with attachment
      headers:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
          description: API key for authentication
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary 
                from:
                  type: string
                to:
                  type: string
                subject:
                  type: string
                title:
                  type: string
                  description: Required if HTML template is sent
                content:
                  type: string
                  description: Required if HTML template is sent
                footer:
                  type: string
                  description: Required if HTML template is sent
                text:
                  type: string
                  description: Required if text email is sent
              required:
                - from
                - to
                - subject
              oneOf:
                - required: [text]
                - required: [content, title, footer]

      responses:
        '201':
          description: Email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Email sent successfully
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Forbidden
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal Server Error
